version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - data:/var/lib/mysql
  nginx:
    image: nginx:latest # Use the latest official Nginx image
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"        # Map HTTP traffic
      - "443:443"      # Map HTTPS traffic
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf # Mount custom Nginx config
      - ./build/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf # Mount custom Nginx config
      - ./build/ssl:/etc/nginx/ssl   # SSL certificates
      - ./bedrock/web:/srv/bedrock/web   # Mount Bedrock web directory
    depends_on:
      - bedrock
  bedrock:
    build:
      context: .
      dockerfile: ./build/bedrock.production.dockerfile # Separate production Dockerfile.
    container_name: bedrock
    restart: unless-stopped
    links:
      - mariadb
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: '${DB_HOST}'
      DB_PREFIX: '${DB_PREFIX}'
      WP_ENV: '${WP_ENV}'
      WP_HOME: '${WP_HOME}'
      WP_SITEURL: '${WP_SITEURL}'
      AUTH_KEY: '${AUTH_KEY}'
      SECURE_AUTH_KEY: '${SECURE_AUTH_KEY}'
      LOGGED_IN_KEY: '${LOGGED_IN_KEY}'
      NONCE_KEY: '${NONCE_KEY}'
      AUTH_SALT: '${AUTH_SALT}'
      SECURE_AUTH_SALT: '${SECURE_AUTH_SALT}'
      LOGGED_IN_SALT: '${LOGGED_IN_SALT}'
      NONCE_SALT: '${NONCE_SALT}'
    volumes:
      - ./bedrock:/srv/bedrock
    depends_on:
      - mariadb
volumes:
  data:
    driver: local # You may need more robust storage options like NFS, AWS S3 etc.